In [1]:
import pandas as pd
import nltk

# Predicting Authorship of the Disputed Federalist Papers

The Federalist Papers are a collection of **85 essays** written by James Madison, Alexander Hamilton, and John Jay under the collective pseudonym "Publius" to promote the ratification of the United States Constitution.

Authorship of most of the papers were revealed some years later by Hamilton, though his claim to authorshipt of 12 papers were disputed for nearly 200 years (studies generally agree that the disputed essays were written by James Madison.)

| Author | Papers |
| :- | -: | 
| Jay | 2, 3, 4, 5, 64
| Madison | 10, 14, 37-48
| Hamilton | 1, 6, 7, 8, 9, 11, 12, 13, 15, 16, 17, 21-36, 59, 60, 61, 65-85
| Hamilton and Madison | 18, 19, 20
| Disputed | 49-58, 62, 63

The goal of this problem is to train a classifier that predicts the author of the disputed papers.

In [2]:
# load Federalist papers data
url = 'https://raw.githubusercontent.com/um-perez-alvaro/Data-Science-Practice/master/Data/papers.csv'
data = pd.read_csv(url)
data.head()

                                               paper    author
0   To the People of the State of New York:  AFTE...  Hamilton
1   To the People of the State of New York:  WHEN...       Jay
2   To the People of the State of New York:  IT I...       Jay
3   To the People of the State of New York:  MY L...       Jay
4   To the People of the State of New York:  QUEE...       Jay

In [3]:
# Federalist paper No. 1
print(data.paper[0])

 To the People of the State of New York:  AFTER an unequivocal experience of the inefficacy of the subsisting federal government, you are called upon to deliberate on a new Constitution for the United States of America. The subject speaks its own importance; comprehending in its consequences nothing less than the existence of the UNION, the safety and welfare of the parts of which it is composed, the fate of an empire in many respects the most interesting in the world. It has been frequently remarked that it seems to have been reserved to the people of this country, by their conduct and example, to decide the important question, whether societies of men are really capable or not of establishing good government from reflection and choice, or whether they are forever destined to depend for their political constitutions on accident and force. If there be any truth in the remark, the crisis at which we are arrived may with propriety be regarded as the era in which that decision is to be made; and a wrong election of the part we shall act may, in this view, deserve to be considered as the general misfortune of mankind.  This idea will add the inducements of philanthropy to those of patriotism, to heighten the solicitude which all considerate and good men must feel for the event. Happy will it be if our choice should be directed by a judicious estimate of our true interests, unperplexed and unbiased by considerations not connected with the public good. But this is a thing more ardently to be wished than seriously to be expected. The plan offered to our deliberations affects too many particular interests, innovates upon too many local institutions, not to involve in its discussion a variety of objects foreign to its merits, and of views, passions and prejudices little favorable to the discovery of truth.  Among the most formidable of the obstacles which the new Constitution will have to encounter may readily be distinguished the obvious interest of a certain class of men in every State to resist all changes which may hazard a diminution of the power, emolument, and consequence of the offices they hold under the State establishments; and the perverted ambition of another class of men, who will either hope to aggrandize themselves by the confusions of their country, or will flatter themselves with fairer prospects of elevation from the subdivision of the empire into several partial confederacies than from its union under one government.  It is not, however, my design to dwell upon observations of this nature. I am well aware that it would be disingenuous to resolve indiscriminately the opposition of any set of men (merely because their situations might subject them to suspicion) into interested or ambitious views. Candor will oblige us to admit that even such men may be actuated by upright intentions; and it cannot be doubted that much of the opposition which has made its appearance, or may hereafter make its appearance, will spring from sources, blameless at least, if not respectable--the honest errors of minds led astray by preconceived jealousies and fears. So numerous indeed and so powerful are the causes which serve to give a false bias to the judgment, that we, upon many occasions, see wise and good men on the wrong as well as on the right side of questions of the first magnitude to society. This circumstance, if duly attended to, would furnish a lesson of moderation to those who are ever so much persuaded of their being in the right in any controversy. And a further reason for caution, in this respect, might be drawn from the reflection that we are not always sure that those who advocate the truth are influenced by purer principles than their antagonists. Ambition, avarice, personal animosity, party opposition, and many other motives not more laudable than these, are apt to operate as well upon those who support as those who oppose the right side of a question. Were there not even these inducements to moderation, nothing could be more ill-judged than that intolerant spirit which has, at all times, characterized political parties. For in politics, as in religion, it is equally absurd to aim at making proselytes by fire and sword. Heresies in either can rarely be cured by persecution.  And yet, however just these sentiments will be allowed to be, we have already sufficient indications that it will happen in this as in all former cases of great national discussion. A torrent of angry and malignant passions will be let loose. To judge from the conduct of the opposite parties, we shall be led to conclude that they will mutually hope to evince the justness of their opinions, and to increase the number of their converts by the loudness of their declamations and the bitterness of their invectives. An enlightened zeal for the energy and efficiency of government will be stigmatized as the offspring of a temper fond of despotic power and hostile to the principles of liberty. An over-scrupulous jealousy of danger to the rights of the people, which is more commonly the fault of the head than of the heart, will be represented as mere pretense and artifice, the stale bait for popularity at the expense of the public good. It will be forgotten, on the one hand, that jealousy is the usual concomitant of love, and that the noble enthusiasm of liberty is apt to be infected with a spirit of narrow and illiberal distrust. On the other hand, it will be equally forgotten that the vigor of government is essential to the security of liberty; that, in the contemplation of a sound and well-informed judgment, their interest can never be separated; and that a dangerous ambition more often lurks behind the specious mask of zeal for the rights of the people than under the forbidden appearance of zeal for the firmness and efficiency of government. History will teach us that the former has been found a much more certain road to the introduction of despotism than the latter, and that of those men who have overturned the liberties of republics, the greatest number have begun their career by paying an obsequious court to the people; commencing demagogues, and ending tyrants.  In the course of the preceding observations, I have had an eye, my fellow-citizens, to putting you upon your guard against all attempts, from whatever quarter, to influence your decision in a matter of the utmost moment to your welfare, by any impressions other than those which may result from the evidence of truth. You will, no doubt, at the same time, have collected from the general scope of them, that they proceed from a source not unfriendly to the new Constitution. Yes, my countrymen, I own to you that, after having given it an attentive consideration, I am clearly of opinion it is your interest to adopt it. I am convinced that this is the safest course for your liberty, your dignity, and your happiness. I affect not reserves which I do not feel. I will not amuse you with an appearance of deliberation when I have decided. I frankly acknowledge to you my convictions, and I will freely lay before you the reasons on which they are founded. The consciousness of good intentions disdains ambiguity. I shall not, however, multiply professions on this head. My motives must remain in the depository of my own breast. My arguments will be open to all, and may be judged of by all. They shall at least be offered in a spirit which will not disgrace the cause of truth.  I propose, in a series of papers, to discuss the following interesting particulars:  THE UTILITY OF THE UNION TO YOUR POLITICAL PROSPERITY THE INSUFFICIENCY OF THE PRESENT CONFEDERATION TO PRESERVE THAT UNION THE NECESSITY OF A GOVERNMENT AT LEAST EQUALLY ENERGETIC WITH THE ONE PROPOSED, TO THE ATTAINMENT OF THIS OBJECT THE CONFORMITY OF THE PROPOSED CONSTITUTION TO THE TRUE PRINCIPLES OF REPUBLICAN GOVERNMENT ITS ANALOGY TO YOUR OWN STATE CONSTITUTION and lastly, THE ADDITIONAL SECURITY WHICH ITS ADOPTION WILL AFFORD TO THE PRESERVATION OF THAT SPECIES OF GOVERNMENT, TO LIBERTY, AND TO PROPERTY.  In the progress of this discussion I shall endeavor to give a satisfactory answer to all the objections which shall have made their appearance, that may seem to have any claim to your attention.  It may perhaps be thought superfluous to offer arguments to prove the utility of the UNION, a point, no doubt, deeply engraved on the hearts of the great body of the people in every State, and one, which it may be imagined, has no adversaries. But the fact is, that we already hear it whispered in the private circles of those who oppose the new Constitution, that the thirteen States are of too great extent for any general system, and that we must of necessity resort to separate confederacies of distinct portions of the whole.(1) This doctrine will, in all probability, be gradually propagated, till it has votaries enough to countenance an open avowal of it. For nothing can be more evident, to those who are able to take an enlarged view of the subject, than the alternative of an adoption of the new Constitution or a dismemberment of the Union. It will therefore be of use to begin by examining the advantages of that Union, the certain evils, and the probable dangers, to which every State will be exposed from its dissolution. This shall accordingly constitute the subject of my next address.  PUBLIUS

In [4]:
data.author.value_counts()

Hamilton            51
Madison             14
Disputed            12
Jay                  5
Hamilton+Madison     3
Name: author, dtype: int64

**Part 1 (text processing):** remove stop words and punctuations from the papers, and lemmatize them.

In [5]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet


from nltk.corpus import stopwords

stop_words = stopwords.words('english')



import string
punctuation = [punc for punc in string.punctuation]


lemmatizer = WordNetLemmatizer()



from nltk.tokenize import word_tokenize

In [6]:


# process parts of speech function
def process_pos(pos):
    if pos.startswith('J'): # adjectives
        return wordnet.ADJ
    elif pos.startswith('V'): # verbes
        return wordnet.VERB
    elif pos.startswith('N'): # nouns
        return wordnet.NOUN
    elif pos.startswith('R'): # adverbs
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [7]:


for i in range(len(data)):
    text = data.loc[i,'paper']
    words = word_tokenize(text)
    words = [word.lower() for word in words]
    lemmatized_words = [lemmatizer.lemmatize(word, pos=process_pos(pos)) 
                        for word,pos in nltk.pos_tag(words) 
                        if word not in stop_words and word not in punctuation]
    data.loc[i,'processed_text'] = ' '.join(lemmatized_words)

In [8]:
data

,paper,author,processed_text
0,To the People of the State of New York: AFTE...,Hamilton,people state new york unequivocal experience i...
1,To the People of the State of New York: WHEN...,Jay,people state new york people america reflect c...
2,To the People of the State of New York: IT I...,Jay,people state new york new observation people c...
3,To the People of the State of New York: MY L...,Jay,people state new york last paper assign severa...
4,To the People of the State of New York: QUEE...,Jay,people state new york queen anne letter 1st ju...
...,...,...,...
80,To the People of the State of New York: LET ...,Hamilton,people state new york let u return partition j...
81,To the People of the State of New York: THE ...,Hamilton,people state new york erection new government ...
82,To the People of the State of New York: THE ...,Hamilton,people state new york objection plan conventio...
83,To the People of the State of New York: IN T...,Hamilton,people state new york course forego review con...
84,To the People of the State of New York: ACCO...,Hamilton,people state new york accord formal division s...

**Part 2: train-test split**

We'll use the papers written by Hamilton and Madion as the training set, and the disputed papers as the testing set.

In [9]:
data_train = data[data.author.isin(['Hamilton','Madison'])]
data_test = data[data.author=='Disputed']

Extract feature matrices X_train and X_test, and target vector y_train

In [10]:
X_train = data_train.processed_text
y_train = data_train.author
X_test = data_test.processed_text

**Part 3:** build a classification pipeline (count vectorizer + Naive Bayes model) that predicts the author of a paper.

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import GridSearchCV, train_test_split

In [12]:


pipe = Pipeline(steps=[
    ('vect', CountVectorizer()), 
    ('clf', MultinomialNB()) 
])

pipe.fit(X_train,y_train)

Pipeline(steps=[('vect', CountVectorizer()), ('clf', MultinomialNB())])

**Part 4:** Use a grid search to tune the pipeline hyperparameters

In [13]:
params_dic =  {'vect__max_features' : [2000,5000,7000,10000],
               'vect__min_df' : [5,25,50],
               'vect__max_df' : [1.0,0.9,0.8],
               'vect__ngram_range' : [(1,1), (1,2)],
               }

grid = GridSearchCV(pipe,
                    params_dic,
                    scoring='accuracy', 
                    cv=5, 
                    n_jobs=-1,
                    verbose=2)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

/Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning:
80 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
80 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/pipeline.py", line 401, in fit
    Xt = self._fit(X, y, **fit_params_steps)
  File "/Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/pipeline.py", line 359, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages/joblib/memory.py", line 349, in __call__
    return self.func(*args, **kwargs)
  File "/Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/pipeline.py", line 893, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1398, in fit_transform
    raise ValueError("max_df corresponds to < documents than min_df")
ValueError: max_df corresponds to < documents than min_df

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.89230769 0.92307692 0.87692308 0.87692308 0.70769231 0.70769231
 0.89230769 0.92307692 0.87692308 0.87692308 0.70769231 0.70769231
 0.89230769 0.92307692 0.87692308 0.87692308 0.70769231 0.70769231
 0.89230769 0.92307692 0.87692308 0.87692308 0.70769231 0.70769231
 0.87692308 0.90769231 0.89230769 0.89230769        nan        nan
 0.87692308 0.90769231 0.89230769 0.89230769        nan        nan
 0.87692308 0.90769231 0.89230769 0.89230769        nan        nan
 0.87692308 0.90769231 0.89230769 0.89230769        nan        nan
 0.84615385 0.87692308 0.81538462 0.81538462        nan        nan
 0.84615385 0.87692308 0.81538462 0.81538462        nan        nan
 0.84615385 0.87692308 0.81538462 0.81538462        nan        nan
 0.84615385 0.87692308 0.81538462 0.81538462        nan        nan]
  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('vect', CountVectorizer()),
                                       ('clf', MultinomialNB())]),
             n_jobs=-1,
             param_grid={'vect__max_df': [1.0, 0.9, 0.8],
                         'vect__max_features': [2000, 5000, 7000, 10000],
                         'vect__min_df': [5, 25, 50],
                         'vect__ngram_range': [(1, 1), (1, 2)]},
             scoring='accuracy', verbose=2)

In [14]:


grid.best_params_

{'vect__max_df': 1.0,
 'vect__max_features': 2000,
 'vect__min_df': 5,
 'vect__ngram_range': (1, 2)}

In [15]:


best_pipe = grid.best_estimator_

# store the vocabulary of X_train
words = best_pipe['vect'].get_feature_names_out()



best_pipe['clf'].classes_

array(['Hamilton', 'Madison'], dtype='<U8')

**Part 5:** How does your classification model choose between Hamilton and Madison?

In [16]:
ham_word_count = best_pipe['clf'].feature_count_[0,:]
mad_word_count = best_pipe['clf'].feature_count_[1,:]

In [17]:
words = pd.DataFrame({'word' : words,
                      'ham' : ham_word_count, 
                      'mad' : mad_word_count}).set_index('word')
words.head()

            ham   mad
word
abandon     7.0   2.0
ability    12.0   0.0
able       44.0  13.0
abolish    13.0   8.0
abolition   5.0   2.0

In [18]:


# add 1 to the columns counts to avoid dividing by 0


for i in range(len(words)):
    words.iloc[i,0]+=1.0
    words.iloc[i,1]+=1.0

In [19]:
words.dtypes

ham    float64
mad    float64
dtype: object

In [20]:
madsum = words['mad'].sum()

In [21]:

# convert the counts into frequencies
words.ham = words.ham/words.ham.sum()
words.mad = words['mad']/madsum
words.head()



# ratios
words['ham_ratio'] = words.ham/words.mad
words['mad_ratio'] = words.mad/words.ham



words.sort_values(by='mad_ratio', ascending=False).head(20)

                            ham   mad  ham_ratio  mad_ratio
word
judiciary department   0.000080  27.0   0.056237  17.781932
whilst                 0.000040  13.0   0.058400  17.123342
article confederation  0.000100  29.0   0.065448  15.279290
relief                 0.000040   8.0   0.094900  10.537441
exist congress         0.000040   8.0   0.094900  10.537441
although               0.000040   8.0   0.094900  10.537441
executive judiciary    0.000120  22.0   0.103527   9.659321
reform                 0.000060  11.0   0.103527   9.659321
respectively           0.000040   7.0   0.108457   9.220261
federal constitution   0.000080  13.0   0.116800   8.561671
passion interest       0.000060   9.0   0.126533   7.903081
legislative executive  0.000181  25.0   0.136656   7.317668
consequently           0.000100  13.0   0.146000   6.849337
assume                 0.000100  12.0   0.158166   6.322465
enumeration            0.000100  12.0   0.158166   6.322465
confederation          0.000481  57.0   0.159831   6.256606
enlarge                0.000060   7.0   0.162685   6.146841
blend                  0.000060   7.0   0.162685   6.146841
body citizen           0.000060   7.0   0.162685   6.146841
federal state          0.000060   7.0   0.162685   6.146841

In [22]:
words.sort_values(by='ham_ratio', ascending=False).head(20)

                   ham  mad  ham_ratio  mad_ratio
word
upon          0.007482  8.0  17.698794   0.056501
intend        0.000702  1.0  13.285958   0.075267
enough        0.000682  1.0  12.906359   0.077481
kind          0.001725  3.0  10.881832   0.091896
readily       0.000502  1.0   9.489970   0.105374
station       0.000481  1.0   9.110371   0.109765
nomination    0.000481  1.0   9.110371   0.109765
commonly      0.000461  1.0   8.730772   0.114537
matter        0.001344  3.0   8.477706   0.117956
two third     0.000441  1.0   8.351174   0.119744
merchant      0.000421  1.0   7.971575   0.125446
jury          0.001685  4.0   7.971575   0.125446
preference    0.000421  1.0   7.971575   0.125446
formation     0.000401  1.0   7.591976   0.131718
information   0.000401  1.0   7.591976   0.131718
contribute    0.000401  1.0   7.591976   0.131718
community     0.001484  4.0   7.022578   0.142398
total         0.000341  1.0   6.453180   0.154962
pretense      0.000341  1.0   6.453180   0.154962
would likely  0.000341  1.0   6.453180   0.154962

The model checks to see the if the language is more likely to appear in the work of Hamilton or Madison and then assigns the corresponding prediction.

**Part 6:** use your classifier to find who was the most likely author of the 12 disputed essays: Hamilton or Madison.

In [25]:
y_test_pred = best_pipe.predict(X_test)

In [26]:
y_test_pred

array(['Madison', 'Madison', 'Madison', 'Madison', 'Hamilton', 'Madison',
       'Madison', 'Hamilton', 'Madison', 'Madison', 'Madison', 'Madison'],
      dtype='<U8')

In [28]:
pd.Series(y_test_pred).value_counts()

Madison     10
Hamilton     2
dtype: int64

The classifer predicts that ten of the twelve disputed papers were authored by Madison, which agrees with the literature.