In [1]:
import pandas as pd

# Practice problem VII

In [2]:
# load the occupation dataset
url = 'https://raw.githubusercontent.com/um-perez-alvaro/Data-Science-Practice/master/Data/users.csv'
users = pd.read_csv(url, index_col='user_id')
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

What is the mean age per occupation?

In [3]:
users.age.mean()

34.05196182396607

Calculate the number of male and female users per occupation.

In [5]:
users.groupby('occupation').gender.value_counts()

occupation     gender
administrator  M          43
               F          36
artist         M          15
               F          13
doctor         M           7
educator       M          69
               F          26
engineer       M          65
               F           2
entertainment  M          16
               F           2
executive      M          29
               F           3
healthcare     F          11
               M           5
homemaker      F           6
               M           1
lawyer         M          10
               F           2
librarian      F          29
               M          22
marketing      M          16
               F          10
none           M           5
               F           4
other          M          69
               F          36
programmer     M          60
               F           6
retired        M          13
               F           1
salesman       M           9
               F           3
scientist      M          28
               F           3
student        M         136
               F          60
technician     M          26
               F           1
writer         M          26
               F          19
Name: gender, dtype: int64

For each occupation, calculate the minimum and maximum ages.

Hint: use pandas `agg()` method.

In [6]:
users.groupby('occupation').agg(['max', 'min'])

              age     gender     zip_code
              max min    max min      max    min
occupation
administrator  70  21      M   F    V1G4L  02154
artist         48  19      M   F    V5A2B  01945
doctor         64  28      M   M    97405  47401
educator       63  23      M   F    M4J2K  01602
engineer       70  22      M   F    T8H1N  00000
entertainment  50  15      M   F    V3N4P  01040
executive      69  22      M   F    L1V3W  00000
healthcare     62  22      M   F    97232  02154
homemaker      50  20      M   F    96349  17331
lawyer         53  21      M   F    90703  06371
librarian      69  23      M   F    99603  01080
marketing      55  24      M   F    97215  01913
none           55  11      M   F    94619  21206
other          64  13      M   F    V0R2M  02110
programmer     63  20      M   F    98121  01331
retired        73  51      M   F    98257  02903
salesman       66  18      M   F    97408  30011
scientist      55  23      M   F    T8H1N  02113
student        42   7      M   F    R3T5K  01002
technician     55  21      M   F    Y1A6B  02139
writer         60  18      M   F    E2A4H  08534

For each combination of occupation and gender, calculate the mean age.

In [9]:
pd.pivot_table(users, values='age',index='occupation', columns='gender', aggfunc='mean')

gender                 F          M
occupation
administrator  40.638889  37.162791
artist         30.307692  32.333333
doctor               NaN  43.571429
educator       39.115385  43.101449
engineer       29.500000  36.600000
entertainment  31.000000  29.000000
executive      44.000000  38.172414
healthcare     39.818182  45.400000
homemaker      34.166667  23.000000
lawyer         39.500000  36.200000
librarian      40.000000  40.000000
marketing      37.200000  37.875000
none           36.500000  18.600000
other          35.472222  34.028986
programmer     32.166667  33.216667
retired        70.000000  62.538462
salesman       27.000000  38.555556
scientist      28.333333  36.321429
student        20.750000  22.669118
technician     38.000000  32.961538
writer         37.631579  35.346154

Calculate the number of male and female users by occupation. Assign the result to a Series named `gender_occupation`.

- Hint: group by `occupation` and `gender`, and apply the method `count` to the `gender` column

In [12]:
gender_occupation = users.groupby(['occupation','gender']).gender.count()
gender_occupation

occupation     gender
administrator  F          36
               M          43
artist         F          13
               M          15
doctor         M           7
educator       F          26
               M          69
engineer       F           2
               M          65
entertainment  F           2
               M          16
executive      F           3
               M          29
healthcare     F          11
               M           5
homemaker      F           6
               M           1
lawyer         F           2
               M          10
librarian      F          29
               M          22
marketing      F          10
               M          16
none           F           4
               M           5
other          F          36
               M          69
programmer     F           6
               M          60
retired        F           1
               M          13
salesman       F           3
               M           9
scientist      F           3
               M          28
student        F          60
               M         136
technician     F           1
               M          26
writer         F          19
               M          26
Name: gender, dtype: int64

Calculate the number of users by occupation. Assign the result to a Series named `total_occupation`.

- Hint: group by `occupation`, and apply the method `count` to the `gender` column.

In [14]:
total_occupation = users.groupby('occupation').gender.count()
total_occupation

occupation
administrator     79
artist            28
doctor             7
educator          95
engineer          67
entertainment     18
executive         32
healthcare        16
homemaker          7
lawyer            12
librarian         51
marketing         26
none               9
other            105
programmer        66
retired           14
salesman          12
scientist         31
student          196
technician        27
writer            45
Name: gender, dtype: int64

Divide the Series `gender_occupation` by the Series `total_occupation` and multiply the result by 100. This will give you the percentage of male and female users by occupation.

In [15]:
gender_occupation/total_occupation*100

occupation     gender
administrator  F          45.569620
               M          54.430380
artist         F          46.428571
               M          53.571429
doctor         M         100.000000
educator       F          27.368421
               M          72.631579
engineer       F           2.985075
               M          97.014925
entertainment  F          11.111111
               M          88.888889
executive      F           9.375000
               M          90.625000
healthcare     F          68.750000
               M          31.250000
homemaker      F          85.714286
               M          14.285714
lawyer         F          16.666667
               M          83.333333
librarian      F          56.862745
               M          43.137255
marketing      F          38.461538
               M          61.538462
none           F          44.444444
               M          55.555556
other          F          34.285714
               M          65.714286
programmer     F           9.090909
               M          90.909091
retired        F           7.142857
               M          92.857143
salesman       F          25.000000
               M          75.000000
scientist      F           9.677419
               M          90.322581
student        F          30.612245
               M          69.387755
technician     F           3.703704
               M          96.296296
writer         F          42.222222
               M          57.777778
Name: gender, dtype: float64