# Stemming, Lemmatization, and the NLTK Library

In [1]:
import pandas as pd

In [2]:
# toy example
X_train = ['I love the book',
          'This is a great book',
          'The fit is great',
          'I love the shoes']

y_train = ['books','books','clothing','clothing']

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [4]:
pipe = Pipeline(steps=[
    ('vect', CountVectorizer()),
    ('clf', MultinomialNB())
])
pipe.fit(X_train, y_train)

Pipeline(steps=[('vect', CountVectorizer()), ('clf', MultinomialNB())])

In [5]:
# toy testing data
X_test = ['I like the book',
         'Shoes are alright',
         'I love the books',
         'I lost a shoe']
pipe.predict(X_test)

array(['books', 'clothing', 'clothing', 'books'], dtype='<U8')

Our pipeline knows about 'book', but it doesn't know about 'books'

## Stemming

In [6]:
!pip install nltk

Requirement already satisfied: nltk in /Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages (3.8.1)
Requirement already satisfied: click in /Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in /Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in /Users/vanmagnan/opt/anaconda3/lib/python3.8/site-packages (from nltk) (4.65.0)

In [7]:
import nltk # natural language toolkit

nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('omw-1.4') # open multilingual wordnet library
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/vanmagnan/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vanmagnan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/vanmagnan/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt to /Users/vanmagnan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/vanmagnan/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [8]:
# initialize the stemmer

from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

In [9]:
stemmer = PorterStemmer()
word = 'books'

stemmer.stem(word)

'book'

In [10]:
stemmer.stem('organize'), stemmer.stem('organizing'), stemmer.stem('organizes')

('organ', 'organ', 'organ')

In [11]:
phrase = 'I love the books'
words = word_tokenize(phrase)
stemmed_words = [stemmer.stem(word) for word in words]
stemmed_words

['i', 'love', 'the', 'book']

In [12]:
" ".join(stemmed_words)

'i love the book'

## Lemmatization

In [13]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [14]:
lemmatizer = WordNetLemmatizer()

In [15]:
# lemmatizer expects the parts of speech (verb, noun, etc)
lemmatizer.lemmatize('running', pos='v')

'run'

In [16]:
lemmatizer.lemmatize('running', pos='n')

'running'

In [17]:
lemmatizer.lemmatize('better', pos='v')

'better'

In [18]:
lemmatizer.lemmatize('better', pos='r') # adverb

'well'

In [19]:
lemmatizer.lemmatize('better', pos='a') # adjective

'good'

How does averaged perceptron tagger work?

In [20]:
pos_list = nltk.pos_tag(words)

In [21]:
pos_list

[('I', 'PRP'), ('love', 'VBP'), ('the', 'DT'), ('books', 'NNS')]

In [22]:
# process parts of speech

def process_pos(pos):
    if pos.startswith('J'): # adjective
        return 'a'
    elif pos.startswith('V'): # verb
        return 'v'
    elif pos.startswith('N'): 
        return 'n'
    elif pos.startswith('R'):
        return 'r'
    else:
        return 'n'

In [23]:
lemmatized_words = [lemmatizer.lemmatize(word, pos=process_pos(pos))
                   for word, pos in nltk.pos_tag(words)]
lemmatized_words

['I', 'love', 'the', 'book']

## Stopwords removal

In [24]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

In [25]:
stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [26]:
phrase = 'here is an example sentence demonstrating the removal stop words'

words = word_tokenize(phrase)
stripped_phrase = [word for word in words if word not in stop_words]

stripped_phrase

['example', 'sentence', 'demonstrating', 'removal', 'stop', 'words']

In [27]:
" ".join(stripped_phrase)

'example sentence demonstrating removal stop words'

In [28]:
## Punctuation removal

import string
punctuation = [punc for punc in string.punctuation]
punctuation

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [29]:
phrase = 'hello! how are you?'
words = word_tokenize(phrase)
words

['hello', '!', 'how', 'are', 'you', '?']

In [30]:
" ".join([word for word in words if word not in punctuation])

'hello how are you'

## Yelp reviews

In [31]:
url = 'https://raw.githubusercontent.com/um-perez-alvaro/Data-Science-Practice/master/Data/yelp.csv'
data = pd.read_csv(url)[['text', 'stars']]
data

                                                   text  stars
0     My wife took me here on my birthday for breakf...      5
1     I have no idea why some people give bad review...      5
2     love the gyro plate. Rice is so good and I als...      4
3     Rosie, Dakota, and I LOVE Chaparral Dog Park!!...      5
4     General Manager Scott Petello is a good egg!!!...      5
...                                                 ...    ...
9995  First visit...Had lunch here today - used my G...      3
9996  Should be called house of deliciousness!\n\nI ...      4
9997  I recently visited Olive and Ivy for business ...      4
9998  My nephew just moved to Scottsdale recently so...      2
9999  4-5 locations.. all 4.5 star average.. I think...      5

[10000 rows x 2 columns]

Goal: predict the stars in terms of the reviews.

To simplify, we keep only the five star and one star reviews

In [39]:
# keep 5-stars and 1-star review
data = data[data.stars.isin([1,5])].reset_index(drop=True)

In [40]:
data

,text,stars,processed_text
0,My wife took me here on my birthday for breakf...,5,wife take birthday breakfast excellent weather...
1,I have no idea why some people give bad review...,5,idea people give bad review place go show plea...
2,"Rosie, Dakota, and I LOVE Chaparral Dog Park!!...",5,NaN
3,General Manager Scott Petello is a good egg!!!...,5,NaN
4,Drop what you're doing and drive here. After I...,5,NaN
...,...,...,...
4081,Yes I do rock the hipster joints. I dig this ...,5,NaN
4082,Only 4 stars? \n\n(A few notes: The folks that...,5,NaN
4083,I'm not normally one to jump at reviewing a ch...,5,NaN
4084,Let's see...what is there NOT to like about Su...,5,NaN
4085,4-5 locations.. all 4.5 star average.. I think...,5,NaN

In [34]:
data.text.iloc[0]

'My wife took me here on my birthday for breakfast and it was excellent.  The weather was perfect which made sitting outside overlooking their grounds an absolute pleasure.  Our waitress was excellent and our food arrived quickly on the semi-busy Saturday morning.  It looked like the place fills up pretty quickly so the earlier you get here the better.\n\nDo yourself a favor and get their Bloody Mary.  It was phenomenal and simply the best I\'ve ever had.  I\'m pretty sure they only use ingredients from their garden and blend them fresh when you order it.  It was amazing.\n\nWhile EVERYTHING on the menu looks excellent, I had the white truffle scrambled eggs vegetable skillet and it was tasty and delicious.  It came with 2 pieces of their griddled bread with was amazing and it absolutely made the meal complete.  It was the best "toast" I\'ve ever had.\n\nAnyway, I can\'t wait to go back!'

In [36]:
text = data.text.iloc[0]
words = word_tokenize(text)

#lowercase
words = [word.lower() for word in words]

lemmatized_words = [lemmatizer.lemmatize(word, pos=process_pos(pos)) 
                    for word,pos in nltk.pos_tag(words)
                   if word not in stop_words and word not in punctuation]
" ".join(lemmatized_words)

"wife take birthday breakfast excellent weather perfect make sit outside overlook ground absolute pleasure waitress excellent food arrive quickly semi-busy saturday morning look like place fill pretty quickly early get good favor get bloody mary phenomenal simply best 've ever 'm pretty sure use ingredient garden blend fresh order amaze everything menu look excellent white truffle scramble egg vegetable skillet tasty delicious come 2 piece griddle bread amaze absolutely make meal complete best `` toast '' 've ever anyway ca n't wait go back"

In [41]:
for i in range(len(data)):
    text = data.loc[i,'text']
    words = word_tokenize(text)
    words = [word.lower() for word in words]
    lemmatized_words = [lemmatizer.lemmatize(word, pos=process_pos(pos)) 
                    for word,pos in nltk.pos_tag(words)
                   if word not in stop_words and word not in punctuation]
    data.loc[i,'processed_text'] = " ".join(lemmatized_words)

In [42]:
data

,text,stars,processed_text
0,My wife took me here on my birthday for breakf...,5,wife take birthday breakfast excellent weather...
1,I have no idea why some people give bad review...,5,idea people give bad review place go show plea...
2,"Rosie, Dakota, and I LOVE Chaparral Dog Park!!...",5,rosie dakota love chaparral dog park 's conven...
3,General Manager Scott Petello is a good egg!!!...,5,general manager scott petello good egg go deta...
4,Drop what you're doing and drive here. After I...,5,drop 're drive eat go back next day food good ...
...,...,...,...
4081,Yes I do rock the hipster joints. I dig this ...,5,yes rock hipster joint dig place little bit sc...
4082,Only 4 stars? \n\n(A few notes: The folks that...,5,4 star note folk rat place low must isolate in...
4083,I'm not normally one to jump at reviewing a ch...,5,'m normally one jump review chain restaurant e...
4084,Let's see...what is there NOT to like about Su...,5,let 's see ... like surprise stadium well 9.50...
4085,4-5 locations.. all 4.5 star average.. I think...,5,4-5 location .. 4.5 star average .. think ariz...

In [43]:
X = data.processed_text
y = data.stars

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [45]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer # can use either
from sklearn.naive_bayes import MultinomialNB

pipe = Pipeline(steps=[
    ('vect', CountVectorizer()),
    ('clf', MultinomialNB())
])
pipe

Pipeline(steps=[('vect', CountVectorizer()), ('clf', MultinomialNB())])

In [47]:
param_dic = {
    'vect__max_features':[2000,5000,7000,10000],
    'vect__max_df': [1.0,0.9,0.8],
    'vect__min_df': [5,20,50],
    'vect__ngram_range':[(1,1), (1,2)]
}

In [48]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe,
                   param_dic,
                   cv=5,
                   scoring='accuracy',
                   n_jobs=-1)

In [49]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('vect', CountVectorizer()),
                                       ('clf', MultinomialNB())]),
             n_jobs=-1,
             param_grid={'vect__max_df': [1.0, 0.9, 0.8],
                         'vect__max_features': [2000, 5000, 7000, 10000],
                         'vect__min_df': [5, 20, 50],
                         'vect__ngram_range': [(1, 1), (1, 2)]},
             scoring='accuracy')

In [50]:
grid.best_params_

{'vect__max_df': 1.0,
 'vect__max_features': 5000,
 'vect__min_df': 5,
 'vect__ngram_range': (1, 2)}

In [51]:
best_pipe=grid.best_estimator_

from sklearn.metrics import accuracy_score, confusion_matrix
y_test_pred = best_pipe.predict(X_test)
confusion_matrix(y_test,y_test_pred)

array([[147,  32],
       [ 48, 795]])

In [52]:
accuracy_score(y_test,y_test_pred)

0.9217221135029354

### What are the one-star words and the five-star words?

In [55]:
vocab = best_pipe['vect'].get_feature_names_out()
vocab

array(['00', '000', '00pm', ..., 'zinburger', 'zone', 'zucchini'],
      dtype=object)

In [56]:
one_star_word_count = best_pipe['clf'].feature_count_[0]
five_star_word_count = best_pipe['clf'].feature_count_[1]
#dataframe
count_df = pd.DataFrame({'word':vocab,
                        '1_star':one_star_word_count,
                        '5_star':five_star_word_count}).set_index('word')

count_df

           1_star  5_star
word
00           30.0    32.0
000           2.0     9.0
00pm          0.0     7.0
07            3.0     5.0
10           76.0   122.0
...           ...     ...
zen           3.0     3.0
zero         15.0     6.0
zinburger     0.0    10.0
zone          1.0     6.0
zucchini      1.0    10.0

[5000 rows x 2 columns]

In [57]:
# add 1
count_df['1_star'] += 1
count_df['5_star'] += 1

In [59]:
#frequencies
count_df['1_star'] = count_df['1_star']/count_df['1_star'].sum()
count_df['5_star'] = count_df['5_star']/count_df['5_star'].sum()

#ratios
count_df['1_star_ratio'] = count_df['1_star']/count_df['5_star']
count_df['5_star_ratio'] = count_df['5_star']/count_df['1_star']

In [60]:
count_df.sort_values(by='1_star_ratio', ascending=False).head(20)

                    1_star    5_star  1_star_ratio  5_star_ratio
word
poor service      0.000287  0.000006     44.337872      0.022554
ca even           0.000225  0.000006     34.836900      0.028705
service horrible  0.000205  0.000006     31.669909      0.031576
never come        0.000205  0.000006     31.669909      0.031576
horrible service  0.000184  0.000006     28.502918      0.035084
rudely            0.000184  0.000006     28.502918      0.035084
send back         0.000184  0.000006     28.502918      0.035084
one star          0.000369  0.000013     28.502918      0.035084
waste money       0.000184  0.000006     28.502918      0.035084
never return      0.000184  0.000006     28.502918      0.035084
rude              0.001024  0.000039     26.391591      0.037891
horrible          0.001495  0.000058     25.687815      0.038929
poorly            0.000164  0.000006     25.335927      0.039470
incompetent       0.000164  0.000006     25.335927      0.039470
wo back           0.000164  0.000006     25.335927      0.039470
mediocre best     0.000164  0.000006     25.335927      0.039470
disgust           0.000471  0.000019     24.280263      0.041186
even acknowledge  0.000143  0.000006     22.168936      0.045108
far bad           0.000143  0.000006     22.168936      0.045108
bad restaurant    0.000143  0.000006     22.168936      0.045108

In [61]:
count_df.sort_values(by='5_star_ratio', ascending=False).head(20)

                 1_star    5_star  1_star_ratio  5_star_ratio
word
fantastic      0.000041  0.001073      0.038157     26.207843
favorite       0.000102  0.002418      0.042339     23.618634
one favorite   0.000020  0.000407      0.050270     19.892700
perfect        0.000082  0.001565      0.052347     19.103307
yum            0.000020  0.000362      0.056553     17.682400
heaven         0.000020  0.000362      0.056553     17.682400
love place     0.000061  0.000989      0.062098     16.103614
ca wait        0.000041  0.000550      0.074517     13.419679
interesting    0.000020  0.000246      0.083342     11.998771
gelato         0.000020  0.000226      0.090485     11.051500
pasty          0.000020  0.000226      0.090485     11.051500
authentic      0.000041  0.000446      0.091797     10.893621
amaze          0.000123  0.001338      0.091797     10.893621
mozzarella     0.000020  0.000220      0.093147     10.735743
pastry         0.000020  0.000220      0.093147     10.735743
delish         0.000020  0.000220      0.093147     10.735743
dentist        0.000020  0.000220      0.093147     10.735743
juicy          0.000020  0.000220      0.093147     10.735743
amazing        0.000164  0.001746      0.093837     10.656804
service great  0.000041  0.000433      0.094537     10.577864

In [64]:
data[data.processed_text.str.contains('ten minute')].text.iloc[4]

'This is not an Asian Topless Bar. It is an Asian "Tapas" bar. The guys I was traveling with spent the first ten minutes waiting for the show to start and were disappointed when I smacked them all for actually thinking I would take my coworkers to a topless bar. \n\n"Tapas" are little appetizer plates, and Sens is all about getting a little taste of everything. The atmosphere is fantastic - eclectic, moody and very, very cozy (so I recommend reservations). \n\nThe little dishes are about four single servings, so you\'ll want to order several plates! Highly recommend the volcano flamed beef and the sugar cane pork. The food is very flavorful -- but everything is a bit spicy (garlicky-spicy), even the dishes they call "mild." \n\nPlates run about $6-$9 each, and each person in our party ordered 3 or 4 plates...we were all full by the time we left! Definitely get a cocktail, their mixed drink menu is fab (White Sin is absolutely sinful...and absolutely worth the indulgence).'