In [1]:
import pandas as pd

In [2]:
# toy example: 4 documents
X_train = ['call you tonight',
          'call you a cab',
          'please call me... PLEASE',
          'he called the police']
X_train

['call you tonight',
 'call you a cab',
 'please call me... PLEASE',
 'he called the police']

We will use CountVectorizer to convert text into a matrix of word counts

In [3]:
# import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer() # with default parameters

In [4]:
# 'learn the vocabulary'
vect.fit(X_train)

CountVectorizer()

In [5]:
vect.get_feature_names_out()

array(['cab', 'call', 'called', 'he', 'me', 'please', 'police', 'the',
       'tonight', 'you'], dtype=object)

In [6]:
# convert training data into a 'document-term matriox'
X_train_dtm = vect.transform(X_train)

In [7]:
X_train_dtm.toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 2, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0]])

In [10]:
pd.DataFrame(X_train_dtm.toarray(), columns=vect.get_feature_names_out(),index=X_train)

,cab,call,called,he,me,please,police,the,tonight,you
call you tonight,0,1,0,0,0,0,0,0,1,1
call you a cab,1,1,0,0,0,0,0,0,0,1
please call me... PLEASE,0,1,0,0,1,2,0,0,0,0
he called the police,0,0,1,1,0,0,1,1,0,0

In [11]:
vect?

In [12]:
X_test = ["please don't call me"]
X_test_dtm = vect.transform(X_test)
pd.DataFrame(X_test_dtm.toarray(), columns=vect.get_feature_names_out(),index=X_test)

,cab,call,called,he,me,please,police,the,tonight,you
please don't call me,0,1,0,0,1,1,0,0,0,0

## Tuning the vectorizer

**stop_words:** Stop words are words like I, a, an, the, this, etc.

In [14]:
vect = CountVectorizer(stop_words='english')
vect.fit(X_train)
vect.get_feature_names_out()

array(['cab', 'called', 'police', 'tonight'], dtype=object)

In [15]:
# list of scikit leran stop words
from sklearn.feature_extraction import _stop_words
print(_stop_words.ENGLISH_STOP_WORDS)

frozenset({'these', 'why', 'someone', 'sometimes', 'third', 'whose', 'whither', 'hereupon', 'due', 'fifty', 'fire', 'herein', 'interest', 'now', 'within', 'formerly', 'something', 'a', 'both', 'nevertheless', 'co', 'your', 'which', 'themselves', 'though', 'ten', 'been', 'already', 'four', 'beside', 'would', 'get', 'never', 'as', 'inc', 'other', 'then', 'whatever', 'also', 'cant', 'keep', 'ourselves', 'side', 'into', 'latter', 'had', 'last', 'amount', 'of', 'up', 'upon', 'thereby', 'thick', 'twenty', 'becomes', 'wherever', 'could', 'anywhere', 'thereafter', 'those', 'eleven', 'do', 'please', 'it', 'off', 'hereby', 'be', 'without', 'indeed', 'three', 'un', 'through', 'six', 'about', 'meanwhile', 're', 'until', 'nobody', 'so', 'can', 'whence', 'couldnt', 'himself', 'everyone', 'are', 'amongst', 'neither', 'in', 'this', 'part', 'to', 'often', 'empty', 'once', 'together', 'us', 'front', 'will', 'an', 'not', 'own', 'well', 'find', 'on', 'thus', 'done', 'top', 'each', 'all', 'seemed', 'over', 'its', 'out', 'beyond', 'around', 'may', 'still', 'whenever', 'what', 'towards', 'although', 'his', 'fill', 'few', 'cannot', 'five', 'myself', 'somehow', 'than', 'there', 'everything', 'ever', 'yourself', 'back', 'found', 'hereafter', 'along', 'we', 'their', 'former', 'bottom', 'at', 'anyway', 'least', 'before', 'him', 'hundred', 'thereupon', 'twelve', 'con', 'anyone', 'latterly', 'becoming', 'ltd', 'me', 'none', 'others', 'ours', 'against', 'must', 'have', 'became', 'has', 'and', 'made', 'move', 'therein', 'another', 'throughout', 'when', 'therefore', 'show', 'with', 'mine', 'system', 'such', 'between', 'most', 'moreover', 'across', 'give', 'bill', 'am', 'somewhere', 'anything', 'per', 'whereby', 'but', 'during', 'itself', 'by', 'being', 'her', 'go', 'seem', 'that', 'only', 'first', 'besides', 'my', 'he', 'here', 'whereas', 'from', 'fifteen', 'via', 'enough', 'is', 'same', 'beforehand', 'full', 'nowhere', 'whereafter', 'everywhere', 'again', 'any', 'further', 'rather', 'i', 'might', 'them', 'wherein', 'they', 'amoungst', 'ie', 'toward', 'elsewhere', 'should', 'perhaps', 'seems', 'hasnt', 'call', 'or', 'afterwards', 'nor', 'anyhow', 'de', 'almost', 'alone', 'thin', 'sometime', 'even', 'else', 'onto', 'thru', 'forty', 'hence', 'whereupon', 'more', 'above', 'nine', 'no', 'every', 'behind', 'thence', 'very', 'whether', 'under', 'serious', 'seeming', 'were', 'among', 'otherwise', 'either', 'describe', 'too', 'eg', 'several', 'whoever', 'she', 'if', 'take', 'except', 'you', 'mostly', 'cry', 'become', 'however', 'yourselves', 'detail', 'eight', 'sincere', 'yours', 'one', 'put', 'namely', 'next', 'below', 'who', 'many', 'how', 'for', 'nothing', 'because', 'down', 'where', 'some', 'was', 'always', 'less', 'hers', 'whole', 'two', 'name', 'mill', 'after', 'since', 'yet', 'our', 'whom', 'noone', 'much', 'sixty', 'herself', 'etc', 'see', 'while', 'the'})

**ngram_range:**

In [18]:
vect=CountVectorizer(ngram_range = (1,3)) # 1 grams, 2 grams, and 3 grams

vect.fit(X_train)
vect.get_feature_names_out()

array(['cab', 'call', 'call me', 'call me please', 'call you',
       'call you cab', 'call you tonight', 'called', 'called the',
       'called the police', 'he', 'he called', 'he called the', 'me',
       'me please', 'please', 'please call', 'please call me', 'police',
       'the', 'the police', 'tonight', 'you', 'you cab', 'you tonight'],
      dtype=object)

**max_df:**

In [19]:
# ignore terns that appear in more than 50% of the documents
vect = CountVectorizer(max_df=0.5)
vect.fit(X_train)
vect.get_feature_names_out()

array(['cab', 'called', 'he', 'me', 'please', 'police', 'the', 'tonight',
       'you'], dtype=object)